### ISSUE TITLE
Title and Footer

### ISSUE THREAD

**Issue by InezHernandez** [cs361fall2018/project-team-36#14]
In charge of styling the title "BATTLESHIP", and also the components in the top right (instructions and key). In charge of footer and reset button

**Comment by peterkyl** [comment]
Instructions should have a popup with some brief game instructions. The key for hit, miss, sink should use colours rather than O, X.

**Comment by peterkyl** [comment]
I added the features I previously described, @johnsja7 should review my changes and make sure it matches the design, making modifications as needed, before closing this issue.

**Comment by johnsja7** [comment]
I reviewed your additions to the header and they look good. I don't see any modification that need to be made. I am closing the issue now.
