### ISSUE TITLE
Result and output of attacks

### ISSUE THREAD

**Issue by InezHernandez** [cs361fall2018/project-team-36#16]
In charge of implementation of popup box for illegal moves and displaying result of each move and of the game.

**Comment by peterkyl** [comment]
Might be nice to add messages for ships being placed. It could also have 2 messages, 1 for player moves and 1 for opponent moves, rather than just showing the opponent moves.

**Comment by baltazarO** [comment]
Okay Kyle I will work on that...

**Comment by baltazarO** [comment]
We got want we mostly wanted
