### ISSUE TITLE
Error with being able to click on CQ

### ISSUE THREAD

**Issue by baltazarO** [cs361fall2018/project-team-36#43]
The game is not letting me click on a CQ twice, for bigger ships. Talked to Caius and he said to make unit tests for the Board (Board test) and simulate the attacks and responses.

**Comment by baltazarO** [comment]
Which I will work on.

**Comment by peterkyl** [comment]
This was an issue were the board class was checking if a square was attacked more than once and throwing an error. We solved the problem in #44 by adding an exception.
