### ISSUE TITLE
Cannot place ships

### ISSUE THREAD

**Issue by baltazarO** [cs361fall2018/project-team-36#45]
The game only lets you place one ship, but no more.

**Comment by peterkyl** [comment]
Found the issue, there is some really semantic notation for the Json properties assigned in the Square.java class. By moving and renaming isCaptain and its getters/setters I solved the issue. Ill try to push the changes to the pull request.

**Comment by peterkyl** [comment]
Pushed the changes to #44. Closing this issue.
